"""Add file_path and rename audio_path

Revision ID: 23cbdfb32459
Revises: 79c6d1e85e01
Create Date: 2026-08-13 19:48:44.266394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cbdfb32459'
down_revision: Union[str, Sequence[str], None] = '79c6d1e85e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diarization', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_column('diarization', 'audio_path')
    op.add_column('youtube_contents', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_contents', 'file_path')
    op.add_column('diarization', sa.Column('audio_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('diarization', 'file_path')
    # ### end Alembic commands ###
