"""add thumbnail, duration, categories and tags to youtube_contents

Revision ID: 321883853f85
Revises: 3968317e02ea
Create Date: 2026-08-07 15:29:59.462048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321883853f85'
down_revision: Union[str, Sequence[str], None] = '3968317e02ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_tracking', 'previous_step',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING_DOWNLOAD', 'DOWNLOADING', 'DOWNLOADED', 'PENDING_METADATA_EXTRACTION', 'EXTRACTING_METADATA', 'COMPLETED', 'ERROR', 'MEMBERS_ONLY', 'AGE_RESTRICTED', 'PRIVATE_VIDEO', 'COPYRIGHT_REMOVED', 'ACCOUNT_TERMINATED', name='contentstep'),
               existing_nullable=True)
    op.alter_column('content_tracking', 'new_step',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING_DOWNLOAD', 'DOWNLOADING', 'DOWNLOADED', 'PENDING_METADATA_EXTRACTION', 'EXTRACTING_METADATA', 'COMPLETED', 'ERROR', 'MEMBERS_ONLY', 'AGE_RESTRICTED', 'PRIVATE_VIDEO', 'COPYRIGHT_REMOVED', 'ACCOUNT_TERMINATED', name='contentstep'),
               existing_nullable=False)
    op.add_column('youtube_contents', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('youtube_contents', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('youtube_contents', sa.Column('categories', sa.JSON(), nullable=True))
    op.add_column('youtube_contents', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_contents', 'tags')
    op.drop_column('youtube_contents', 'categories')
    op.drop_column('youtube_contents', 'duration')
    op.drop_column('youtube_contents', 'thumbnail')
    op.alter_column('content_tracking', 'new_step',
               existing_type=sa.Enum('PENDING_DOWNLOAD', 'DOWNLOADING', 'DOWNLOADED', 'PENDING_METADATA_EXTRACTION', 'EXTRACTING_METADATA', 'COMPLETED', 'ERROR', 'MEMBERS_ONLY', 'AGE_RESTRICTED', 'PRIVATE_VIDEO', 'COPYRIGHT_REMOVED', 'ACCOUNT_TERMINATED', name='contentstep'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('content_tracking', 'previous_step',
               existing_type=sa.Enum('PENDING_DOWNLOAD', 'DOWNLOADING', 'DOWNLOADED', 'PENDING_METADATA_EXTRACTION', 'EXTRACTING_METADATA', 'COMPLETED', 'ERROR', 'MEMBERS_ONLY', 'AGE_RESTRICTED', 'PRIVATE_VIDEO', 'COPYRIGHT_REMOVED', 'ACCOUNT_TERMINATED', name='contentstep'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
