"""add error_info to content_model

Revision ID: 71d99b3e6db4
Revises: ff9d893277fe
Create Date: 2026-07-10 21:19:40.335624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d99b3e6db4'
down_revision: Union[str, Sequence[str], None] = 'ff9d893277fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('error_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'error_info')
    # ### end Alembic commands ###
