"""add_new_content_steps

Revision ID: a22060bc6f25
Revises: d1af7782b2d2
Create Date: 2026-08-08 10:24:51.768368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22060bc6f25'
down_revision: Union[str, Sequence[str], None] = 'd1af7782b2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE contentstep ADD VALUE IF NOT EXISTS 'STARTED'")
        op.execute("ALTER TYPE contentstep ADD VALUE IF NOT EXISTS 'METADATA_EXTRACTED'")
        op.execute("ALTER TYPE contentstep ADD VALUE IF NOT EXISTS 'DOWNLOADED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
