"""Add language column to youtube_contents

Revision ID: d07f807ea0f1
Revises: a5b693182f1c
Create Date: 2026-08-13 23:12:10.389067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07f807ea0f1'
down_revision: Union[str, Sequence[str], None] = 'a5b693182f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_contents', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_contents', 'language')
    # ### end Alembic commands ###
