"""create youtube_channels table

Revision ID: d1af7782b2d2
Revises: 7888c82e90f8
Create Date: 2026-08-07 22:49:04.774139

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d1af7782b2d2"
down_revision: Union[str, Sequence[str], None] = "7888c82e90f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube_channels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("channel_url", sa.String(), nullable=True),
        sa.Column("thumbnails", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        if_not_exists=True,
    )
    op.drop_column("youtube_contents", "source_platform")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_contents",
        sa.Column(
            "source_platform",
            postgresql.ENUM("YOUTUBE", name="sourceplatform"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("youtube_channels", if_exists=True)
    # ### end Alembic commands ###
