"""add_published_at_and_fix_enums

Revision ID: d1b88777f017
Revises: e71df43e477d
Create Date: 2026-08-07 18:23:09.748027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b88777f017'
down_revision: Union[str, Sequence[str], None] = 'e71df43e477d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_contents', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # --- ENUM REBUILD (Remove DOWNLOADED, Ensure VIDEO_REMOVED) ---
    # 1. Update any existing 'DOWNLOADED' records to 'COMPLETED'
    op.execute("UPDATE youtube_contents SET step = 'COMPLETED' WHERE step = 'DOWNLOADED'")
    op.execute("UPDATE content_tracking SET previous_step = 'COMPLETED' WHERE previous_step = 'DOWNLOADED'")
    op.execute("UPDATE content_tracking SET new_step = 'COMPLETED' WHERE new_step = 'DOWNLOADED'")

    # 2. Rename old enum
    op.execute("ALTER TYPE contentstep RENAME TO contentstep_old")

    # 3. Create new enum
    new_enum = (
        "CREATE TYPE contentstep AS ENUM ("
        "'PENDING_DOWNLOAD', 'DOWNLOADING', 'PENDING_METADATA_EXTRACTION', "
        "'EXTRACTING_METADATA', 'COMPLETED', 'ERROR', 'MEMBERS_ONLY', "
        "'AGE_RESTRICTED', 'PRIVATE_VIDEO', 'COPYRIGHT_REMOVED', "
        "'ACCOUNT_TERMINATED', 'VIDEO_REMOVED')"
    )
    op.execute(new_enum)

    # 4. Alter columns to use the new enum
    op.execute("ALTER TABLE youtube_contents ALTER COLUMN step TYPE contentstep USING step::text::contentstep")
    op.execute("ALTER TABLE content_tracking ALTER COLUMN previous_step TYPE contentstep USING previous_step::text::contentstep")
    op.execute("ALTER TABLE content_tracking ALTER COLUMN new_step TYPE contentstep USING new_step::text::contentstep")

    # 5. Drop old enum
    op.execute("DROP TYPE contentstep_old")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_contents', 'published_at')
    # ### end Alembic commands ###
