"""add raw_metadata to youtube_contents

Revision ID: db287817074c
Revises: 75e5ad65bdb9
Create Date: 2026-08-07 14:01:11.667760

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db287817074c"
down_revision: Union[str, Sequence[str], None] = "75e5ad65bdb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_contents", sa.Column("raw_metadata", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_contents", "raw_metadata")
    # ### end Alembic commands ###
