"""Rename status to step in diarization

Revision ID: e0b00fb5e6a5
Revises: be460d82708c
Create Date: 2026-08-13 22:48:59.150305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b00fb5e6a5'
down_revision: Union[str, Sequence[str], None] = 'be460d82708c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diarization', sa.Column('step', sa.String(), nullable=False))
    op.create_index(op.f('ix_diarization_step'), 'diarization', ['step'], unique=False, if_not_exists=True)
    op.drop_column('diarization', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diarization', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_diarization_step'), table_name='diarization', if_exists=True)
    op.drop_column('diarization', 'step')
    # ### end Alembic commands ###
