"""migrate_name_to_external_id_in_monitored_channels

Revision ID: f34b7c26cc9d
Revises: 474bbaa347d1
Create Date: 2026-08-09 13:49:51.820112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34b7c26cc9d'
down_revision: Union[str, Sequence[str], None] = '474bbaa347d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable first
    op.add_column('youtube_monitored_channels', sa.Column('external_id', sa.String(), nullable=True))
    
    # 2. Update existing rows by matching url with youtube_channels
    # The user mentioned querying by url in channel_url or url to get the correct external_id.
    op.execute("""
        UPDATE youtube_monitored_channels 
        SET external_id = yc.external_id 
        FROM youtube_channels yc 
        WHERE youtube_monitored_channels.url = yc.url OR youtube_monitored_channels.url = yc.channel_url
    """)
    
    # Optional: Delete rows that couldn't be mapped to avoid NotNullViolation
    op.execute("DELETE FROM youtube_monitored_channels WHERE external_id IS NULL")
    
    # 3. Make column NOT NULL
    op.alter_column('youtube_monitored_channels', 'external_id', nullable=False)
    
    # 4. Add foreign key
    op.create_foreign_key(None, 'youtube_monitored_channels', 'youtube_channels', ['external_id'], ['external_id'])
    
    # 5. Drop the old column
    op.drop_column('youtube_monitored_channels', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_monitored_channels', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'youtube_monitored_channels', type_='foreignkey')
    op.drop_column('youtube_monitored_channels', 'external_id')
    # ### end Alembic commands ###
