"""create tables

Revision ID: ff9d893277fe
Revises: 
Create Date: 2026-07-08 16:47:30.592462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9d893277fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_platform', sa.Enum('YOUTUBE', name='sourceplatform'), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_DOWNLOAD', 'DOWNLOADING', 'DOWNLOADED', 'ERROR', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_index(op.f('ix_contents_external_id'), 'contents', ['external_id'], unique=True, if_not_exists=True)
    op.create_table('monitored_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_platform', sa.Enum('YOUTUBE', name='sourceplatform'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitored_sources', if_exists=True)
    op.drop_index(op.f('ix_contents_external_id'), table_name='contents', if_exists=True)
    op.drop_table('contents', if_exists=True)
    # ### end Alembic commands ###
