import enum


class ContentStep(str, enum.Enum):
    """Content step in the processing pipeline."""

    PENDING_DOWNLOAD = "PENDING_DOWNLOAD"
    DOWNLOADING = "DOWNLOADING"

    PENDING_METADATA_EXTRACTION = "PENDING_METADATA_EXTRACTION"
    EXTRACTING_METADATA = "EXTRACTING_METADATA"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"
    MEMBERS_ONLY = "MEMBERS_ONLY"
    AGE_RESTRICTED = "AGE_RESTRICTED"
    PRIVATE_VIDEO = "PRIVATE_VIDEO"
    COPYRIGHT_REMOVED = "COPYRIGHT_REMOVED"
    ACCOUNT_TERMINATED = "ACCOUNT_TERMINATED"
    VIDEO_REMOVED = "VIDEO_REMOVED"
