import enum


class ContentStep(str, enum.Enum):
    """Content step in the processing pipeline."""

    STARTED = "STARTED"
    PENDING_METADATA_EXTRACTION = "PENDING_METADATA_EXTRACTION"
    EXTRACTING_METADATA = "EXTRACTING_METADATA"
    METADATA_EXTRACTED = "METADATA_EXTRACTED"

    PENDING_DOWNLOAD = "PENDING_DOWNLOAD"
    DOWNLOADING = "DOWNLOADING"
    DOWNLOADED = "DOWNLOADED"

    COMPLETED = "COMPLETED"
    ERROR = "ERROR"
    REPROCESSING = "REPROCESSING"
    MEMBERS_ONLY = "MEMBERS_ONLY"
    AGE_RESTRICTED = "AGE_RESTRICTED"
    PRIVATE_VIDEO = "PRIVATE_VIDEO"
    COPYRIGHT_REMOVED = "COPYRIGHT_REMOVED"
    ACCOUNT_TERMINATED = "ACCOUNT_TERMINATED"
    VIDEO_REMOVED = "VIDEO_REMOVED"
    DELETED = "DELETED"
