from typing import Any, Protocol

from src.modules.demograph.domain.entities.run import Run


class Catalog(Protocol):
    def run(self, run_id: str) -> Run: ...
    def update(self, run_id: str, **values: Any) -> None: ...
    def artifacts(self, extraction_id: str, dataset: str | None = None) -> list[dict[str, Any]]: ...
    def add_artifact(self, values: dict[str, Any]) -> None: ...
    def issue(self, run_id: str, message: str, context: dict[str, Any]) -> None: ...
    def save_schema(self, run_id: str, schema: dict[str, Any]) -> None: ...
